fixes : #1177 support variable values on open libery alizer's port de…
devfile/alizer pull request #111
Opened 2024-10-15 13:10 UTC by Horiodino

# Description of Changes
resolves the port value by checking if it is a variable and if it is, it returns the value of the variable

# Related Issue(s)
https://github.com/devfile/api/issues/1177

# Acceptance Criteria

_Testing and documentation do not need to be complete in order for this PR to be approved. However, tracking issues must be opened for missing testing/documentation._

- [ ] Unit/Functional tests

  

- [ ] Documentation

   

# Tests Performed
✔️️ Added suitable test case based on Issue.

# How To Test
_Instructions for the reviewer on how to test your changes._

# Notes To Reviewer
_Any notes you would like to include for the reviewer._

2024-10-16 13:46 UTC, Jdubrick requested changes
Overall I like the changes :) just left 1 comment regarding adding a few more test cases to cover all scenarios

2024-10-16 13:46 UTC, Jdubrick commented on pkg/apis/enricher/framework/java/openliberty_detector_test.go
> +	t.Run("Hardcoded Ports", func(t *testing.T) {
Is it possible to add a test case for a mix of hardcoded and variable based ports?

2024-10-16 13:46 UTC, Jdubrick commented on pkg/apis/enricher/framework/java/openliberty_detector_test.go
> +	t.Run("Hardcoded Ports", func(t *testing.T) {
Possibly one for empty var as well?

2024-10-16 13:51 UTC, Jdubrick commented
/ok-to-test

2024-10-22 14:48 UTC, thepetk approved these changes
/lgtm

2024-10-23 17:11 UTC, Jdubrick approved these changes
lgtm with the one comment about running `go mod tidy`

2024-10-23 17:11 UTC, Jdubrick commented on go.mod
> +	gotest.tools v1.4.0
Just need to run `go mod tidy` as @thepetk mentioned

2024-10-28 13:45 UTC, Jdubrick approved these changes
lgtm

2024-10-28 13:59 UTC, merged