[Devtools Week] Update contributing guide
devfile/alizer pull request #39
Opened 2023-12-11 16:35 UTC by thepetk

## What does this PR do?

This PR updates the `contributing.md` in order to be more consistent with the rest of the `contributing.md` files inside the `Devfile` organization. The updated document follows the `contributing.md` file of the `registry-support` repo ([here](https://github.com/devfile/registry-support/blob/main/CONTRIBUTING.md))

### Which issue(s) does this PR fix

Part of the devtools week

### PR acceptance criteria

Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.

- [ ] Unit/Functional tests
- [ ] Documentation

### How to test changes / Special notes to the reviewer

2023-12-11 19:10 UTC, michael-valdron requested changes

2023-12-11 19:10 UTC, michael-valdron commented on CONTRIBUTING.md
> +If you have questions, please visit us on `#devfile` in the [Kubernetes Slack](https://slack.k8s.io).
```suggestion
If you have any questions, please visit us the `#devfile` channel under the [Kubernetes Slack](https://slack.k8s.io) workspace.
```

2023-12-11 19:10 UTC, michael-valdron commented on CONTRIBUTING.md
> +After addressing review comments, don't forget to add a comment in the PR afterward, so everyone gets notified by Github and know to re-review.
@thepetk I'm thinking the author should mention the reviewer in their comment so the reviewer can provide a follow up review, wdyt?

```suggestion
After addressing review comments, don't forget to add a comment in the PR with the reviewer mentioned afterward, so they get notified by Github to provide a re-review.
```

2023-12-11 19:10 UTC, michael-valdron commented on CONTRIBUTING.md
> +Owners of the repository will watch out for and review new PRs.
```suggestion
Owners of the repository will watch out for new PRs and provide reviews to them.
```

2023-12-12 11:23 UTC, thepetk commented on CONTRIBUTING.md
> +By default for each change in the PR, GitHub Actions and OpenShift CI will run checks against your changes (linting, unit testing, and integration tests).
@michael-valdron I've removed the openshift CI as is doesn't exist as a check and added the code coverage checks.

2023-12-12 11:24 UTC, thepetk commented
@michael-valdron I've addressed your suggestions :) thanks for the review

2023-12-15 16:09 UTC, michael-valdron approved these changes
/lgtm

2023-12-15 16:25 UTC, merged